Repository opensearch-project/opensearch-devops, pull requests merged in 2021-08, with the labels that each got.

#29 Add secret mounts to values
  Helm/opensearch-dashboards/values.yaml
Labels: bug

#33 Persistence config
  Helm/opensearch/templates/statefulset.yaml
  Helm/opensearch/values.yaml
Labels: bug

#34 Add and update opensearch-devops related documents
  ADMINS.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEVELOPER_GUIDE.md
  LICENSE.txt
  MAINTAINERS.md
  NOTICE
  NOTICE.txt
  README.md
Labels: documentation

#31 add configSecret Volumes
  Helm/opensearch/templates/statefulset.yaml
Labels: bug

#47 support for current ingress apiVersion
  Helm/opensearch-dashboards/templates/ingress.yaml
Labels: enhancement

#35 Helm Chart Fixes for Env variables and volumes
  Helm/opensearch-dashboards/templates/deployment.yaml
  Helm/opensearch/templates/statefulset.yaml
  Helm/opensearch/values.yaml
Labels: bug

#38 Fixing config path in opensearch-dashboards
  Helm/opensearch-dashboards/templates/deployment.yaml
  Helm/opensearch-dashboards/values.yaml
Labels: bug

#56 Fix helm chart can not be deployed without ssl
  Helm/opensearch-dashboards/values.yaml
Labels: bug
